### ISSUE TITLE
首页左侧下拉框选择版本 依然存在溢出问题

### ISSUE THREAD

**Issue by aron0524** [HGthecode/apidoc-ui#19]
不知道是不是您这边vue打包的问题 用了最新的 后端插件3.0.2 前端组件2.0.3依然存在该问题。

**Comment by aron0524** [comment]
浏览器 chrome
版本 90.0.4430.72（正式版本） （64 位）
Chrome++ 1.4.0 inside

**Comment by HGthecode** [comment]
我在演示站上放了一些测试用的应用配置，你可以看看，有没有出现你说的问题[https://apidoc.demo.hg-code.com/apidoc/](https://apidoc.demo.hg-code.com/apidoc/)

**Comment by aron0524** [comment]
不是那种配置会出问题。

        [
            'title'=>'test_1',
            'path'=>'app\test_1\controller',
            'folder'=>'test_1',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\test_1\controller\v1','folder'=>'v1'],
                ['title'=>'V2.0','path'=>'app\test_1\controller\v2','folder'=>'v2']
            ]
        ],
        [
            'title'=>'test_2',
            'path'=>'app\test_2\controller',
            'folder'=>'test_2',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\test_2\controller\v1','folder'=>'v1']
            ]
        ],
        [
            'title'=>'test_3',
            'path'=>'app\test_3\controller',
            'folder'=>'test_3',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\test_3\controller\v1','folder'=>'v1']
            ]
        ],
        [
            'title'=>'test_4',
            'path'=>'app\test_4\controller',
            'folder'=>'test_4',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\test_4\controller\v1','folder'=>'v1']
            ]
        ],
        [
            'title'=>'test_5',
            'path'=>'app\test_5\controller',
            'folder'=>'test_5',
            'items'=>[
                ['title'=>'V1.0','path'=>'app\test_5\controller\v1','folder'=>'v1']
            ]
        ],

您可以尝试这样配置看看。

**Comment by HGthecode** [comment]
我现在重新构建了一份上传了，你可以刷新文档后，重新下载最新的试试

**Comment by HGthecode** [comment]
我试试你这种配置，找出问题，稍后再更新哈

**Comment by aron0524** [comment]
好的。感谢。

**Comment by HGthecode** [comment]
已更新了，你可以重新下载前端文件即可
