### ISSUE TITLE
标签页关闭，左侧菜单选中状态未取消

### ISSUE THREAD

**Issue by chunshand** [HGthecode/apidoc-ui#20]
版本 2.0.10

![image](https://user-images.githubusercontent.com/20159933/146854921-7febb637-e45c-41fd-94fa-9f61fdd86a48.png)

点击关闭标签页 再次点击 获取用户消息 则无反应 

并不是大问题 只是一个小体验的问题

**Comment by HGthecode** [comment]
你好，更新到最新版前端，已解决了该问题

**Comment by chunshand** [comment]
新版测试ok
