### ISSUE TITLE
setGlobalHeader 当value=undefined时照样会设置值

### ISSUE THREAD

**Issue by martin-yeung** [HGthecode/apidoc-ui#21]
需求场景：使用jwt做token验证时，需要实现无感刷新，实现的方式就是当token过期但refresh_token没过期则后端生成新的token并输出到response.headers.authorization中……然后apidoc需要保存新的token到全局并设置到header。目前代码不能实现，做了如图修改。相应的还有其他的几个set。因为有clear所以设置为undefined应该不需要。
![image](https://user-images.githubusercontent.com/53016934/228223963-81a8469d-1906-4b32-a920-5537bc4d54e4.png)

**Comment by HGthecode** [comment]
![image](https://user-images.githubusercontent.com/36032426/228489622-569d3fcf-cc1f-41ae-9ead-9a5678dd73c8.png)

新版本的前端这个方法是这样的

**Comment by HGthecode** [comment]
你什么场景会执行到设置一个undefined？

**Comment by martin-yeung** [comment]
是的，我就是用的最新版。就是在做jwt无感刷新的时候，当后端检测到token过期且能刷新，就把新token输出到response.header里面，前端就把新获取的token存在来，做下一次请求时使用。但如果token还没过期，那么response的header里就不会有这个token的输出，因此就是undefined
是下图中这么用的，我已经修改了代码，暂时实现了
![image](https://user-images.githubusercontent.com/53016934/228633306-22a9e296-fb81-4319-a7a2-8c31b49f23da.png)
前面那个注释了的方法checkResponseHeaderAuthorization，是我自己在ui的config文件中实现的，可以读取到返回的token，但无法保存到Global的Header变量中

**Comment by HGthecode** [comment]
已修复，请下载最新的前端文件即可

**Comment by martin-yeung** [comment]
thanks
